### ISSUE TITLE
builtin funtions and C functions can not be used as RPC methods

### ISSUE THREAD

**Issue by semigodking** [pengutronix/aiohttp-json-rpc#35]
In latest version, C functions can not be used as RPC methods anymore. Builtin functions are C functions. 
For no reason we use builtins as RPC methods. But, we do want to use C extensions. Wrapping C extensions within python functions is not good idea if there are many extensions.
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> inspect.getfullargspec(min)
Traceback (most recent call last):
  File "/usr/lib/python3.6/inspect.py", line 1116, in getfullargspec
    sigcls=Signature)
  File "/usr/lib/python3.6/inspect.py", line 2262, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/usr/lib/python3.6/inspect.py", line 2087, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function min>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/inspect.py", line 1122, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

I also tried a Cython compiled module with source as:
``` python
def func1(a, b):
    return a + b
```
It is the same.
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> import t
>>> inspect.getfullargspec(t.func1)
Traceback (most recent call last):
  File "/usr/lib/python3.6/inspect.py", line 1116, in getfullargspec
    sigcls=Signature)
  File "/usr/lib/python3.6/inspect.py", line 2262, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/usr/lib/python3.6/inspect.py", line 2087, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function func1>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/inspect.py", line 1122, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
>>> t.func1(1, 2)
3
>>>

```

**Comment by fscherf** [comment]
Huh interesting! First of all: Thanks for reporting. I've never used cython in one of my rpc projects. The inspect code came in in pr #33.
Do you have ideas how inspecting could work with cython? Otherwise i have to make the all introspection optional.

btw: in pr #31 you requested the support of synchronous rpc methods which i rejected. Running synchronous code on the rpc is now possible. I will update the docs when i have time

**Comment by semigodking** [comment]
I am afraid there's no way to inspect C functions unless debug infomation
is compiled into .so files. Maybe you can try inspection and fall back to
old implementation when inspection failed.

**Comment by fscherf** [comment]
hi @semigodking,

I am sorry that it took me so long, but i pushed v0.11.1, with a fallback mode for non introspectable rpc methods

**Comment by fscherf** [comment]
@semigodking can i close this issue now?

**Comment by semigodking** [comment]
Sure! Thank you!
