### ISSUE TITLE
concurrent.futures._base.TimeoutError

### ISSUE THREAD

**Issue by Noor-Kalibbala** [pengutronix/aiohttp-json-rpc#58]
how do we supply timeout parameter so the i eleiminate this annoying error
Traceback (most recent call last):
  File "server.py", line 47, in handle_conversation
    answer = await Engine.get_answer(decoded_data["Task"], decoded_data["content"])
  File "/home/netlabsug/PycharmProjects/untitled1/mak_polls/Engine.py", line 193, in get_answer
    answer = await function(content)
  File "/home/netlabsug/PycharmProjects/untitled1/mak_polls/Engine.py", line 66, in post
    method_res = await jrpc.post(doc)
  File "/home/netlabsug/PycharmProjects/makpolls/venv/lib/python3.7/site-packages/aiohttp_json_rpc/client.py", line 174, in call
    await asyncio.wait_for(self._pending[id], timeout=timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by fscherf** [comment]
Hi @Noor-Kalibbala,

`aiohttp_json_rpc.client.Client.call()` by default uses `asyncio.wait_for()` with a timeout of `1`.
It seems like you are running in this timeout. If you want a longer timeout:

``client.call($YOUR_CALL, timeout=1000)``

If you want no timeout at all:

``client.call($YOUR_CALL, timeout=None)``

**Comment by Noor-Kalibbala** [comment]
@fscherf  eventhough u change this timeout to something big, it will still through the error, the problem was that l was sending a big json file causing the server to cat weirdly

**Comment by fscherf** [comment]
@Noor-Kalibbala 
OK. You opened another issue on problems with large json blobs. Are you ok with me closing this issue and we discuss this problem in the other thread?

**Comment by Noor-Kalibbala** [comment]
Its okay u can close
